config/routes.rb
MailboxPlusServer::Application.routes.draw do

  resources :messages do
         collection do
           post :delete_selected
           post :send_new
         end
       end
       
  resources :mailboxes do
    member do
      get 'nearby'
    end
    collection do
      get 'community'
    end
  end

  resources :stamps do
    collection do
      get 'buy'
      get 'batch_generate'
      get 'batch_delete'
    end
  end

  devise_for :users, :controllers => { :sessions => "sessions" }
 
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end
  
  
  

  
  resources :token_authentications, :only => [:create, :destroy]
  
  root :to => "base#index"
  
  
end

app/models/message.rb
class Message < ActiveRecord::Base

  is_private_message
  
  # The :to accessor is used by the scaffolding,
  # uncomment it if using it or you can remove it if not
  #attr_accessor :to
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_user
  respond_to :html, :json
  
  def index
    #if params[:mailbox] == "sent"
      @messages_sent = @user.sent_messages
    #else
      @messages_received = @user.received_messages
    #end
  end
  
  def show
    @message = Message.read_message(params[:id], current_user)
  end
  
  def new
    @message = Message.new

    if params[:reply_to]
      @reply_to = @user.received_messages.find(params[:reply_to])
      unless @reply_to.nil?
        @message.to = @reply_to.sender.login
        @message.subject = "Re: #{@reply_to.subject}"
        @message.body = "\n\n*Original message*\n\n #{@reply_to.body}"
      end
    end
  end
  
  def send_new
    @message = Message.new()
    @message.body = params[:text]
    @message.sender = current_user
    @message.recipient = User.find(params[:recipient_id])

    @message.save
  end
  
  def create
    @message = Message.new(params[:message])
    @message.sender = @user
    @message.recipient = User.find_by_login(params[:message][:to])

    if @message.save
      flash[:notice] = "Message sent"
      redirect_to user_messages_path(@user)
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(:first, :conditions => ["messages.id = ? AND (sender_id = ? OR recipient_id = ?)", id, @user, @user])
          @message.mark_deleted(@user) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to :back
    end
  end
  
  private
    def set_user
      @user = current_user || User.find(params[:user_id])
    end
end

app/views/messages/_inbox.html.erb
<table id="tabletabs-2" class="tables ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
	<tr>
		<th>Del?</th>
		<th>Sent</th>
		<th>Sender</th>
		<th>Sent</th>
	</tr>
	<% if @messages_received.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages_received %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if message.message_read? %>
					  <%= link_to h(message.subject), message_path(@user, message) %>
					<% else %>
					  <%= link_to "#{h(message.subject)} (unread)", message_path(@user, message) %>
					<% end %>
				</td>
				<td><%= h(message.sender.email) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>

app/views/messages/_sent.html.erb
<table id="tabletabs-1" class="tables ui-tabs-panel ui-widget-content ui-corner-bottom">
	<tr>
		<th>Del?</th>
		<th>Subject</th>
		<th>To</th>
		<th>Sent</th>
	</tr>
	<% if @messages_sent.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<% for message in @messages_sent %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(message.body), message_path( message) %></td>
  			<td><%= h(message.recipient.first_name)  %></td>
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
 	<% end %>
</table>

app/views/messages/index.html.erb
<script type="text/javascript">
$(function() {
    makeTabActive("inbox");
    
	$( "#tabletabs" ).tabs();
    
    });
    
    

</script>

<!-- 
	<a href="messages/new" class="simple_buttons">Compose</a>
-->


<div class="g_12">
					
					<h2>Listing my mailboxes</h2>

<%= form_tag delete_selected_messages_path(@user, :method => :post) do %>
	

<div id="tabletabs" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
					<div class="widget_header wwOptions">
						<h4 class="widget_header_title wwIcon i_16_tabs">Messages</h4>
						<ul class="w_Tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
							<li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active"><a title="Tab 1" href="#tabletabs-1">Inbox</a></li>
							<li class="ui-state-default ui-corner-top"><a title="Tab 2" href="#tabletabs-2">Sent</a></li>
						</ul>
					</div>
					<div class="widget_contents noPadding">
						
						<%= render :partial => "messages/inbox" %>
						<%= render :partial => "sent" %>
						
					</div>
</div>     </div>


<% end %>

app/views/messages/new.html.erb
<% form_for @message, :url => messages_path do |f| %>
  <p>
    To:<br />
		<%= f.text_field :to %>
		<%= error_message_on @message, :to %>
  </p>
  <p>
    Subject:<br />
    <%= f.text_field :subject %>
    <%= error_message_on @message, :subject %>
    </p>
    <p>
      Message<br />
      <%= f.text_area :body %>
			<%= error_message_on @message, :body %>
    </p>
    <p>
      <%= submit_tag "Send" %>
    </p>
<% end %>

app/views/messages/show.html.erb
<p><strong>From:</strong> <%= @message.sender == @user ? link_to("You", user_path(@user)) : link_to(h(@message.sender.login), user_path(@message.sender)) %></p>
<p><strong>Received:</strong> <%= @message.created_at.to_s(:long) %></p>
<p><strong>To:</strong> <%= @message.recipient == @user ? link_to("You", user_path(@user)) : link_to(h(@message.recipient.login), user_path(@message.recipient)) %></p>
<p>
  <strong>Message</strong><br />
  <%=h @message.body %>
</p>
<p>
  <% if @message.recipient == @user %>
	  <%= link_to "Reply", new_user_message_path(@user, :reply_to => @message) %> |
  <% end %>
  <%= link_to "Inbox", user_messages_path(@user)%>
</p>