config/routes.rb
MailboxPlusServer::Application.routes.draw do

  resources :messages do
         collection do
           post :delete_selected
           post :send_new
         end
       end
       
  resources :mailboxes do
    member do
      get 'nearby'
    end
    collection do
      get 'community'
    end
  end

  resources :stamps do
    collection do
      get 'buy'
      get 'batch_generate'
      get 'batch_delete'
    end
  end

  devise_for :users, :controllers => { :sessions => "sessions" }
 
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end
  
  
  

  
  resources :token_authentications, :only => [:create, :destroy]
  
  root :to => "base#index"
  
  
end

app/models/mailbox.rb
require 'qrcode'

class Mailbox < ActiveRecord::Base
  
  
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  
  attr_accessible :qrcode, :user_id, :name, :street, :city, :country, :state, :zipcode, :complement, :latitude, :longitude
  
  belongs_to :user
  
  after_create :generate_qrcode
  
  validates_presence_of :name
  
  
  def generate_qrcode
    # generates the qrcode image based on the assigned id of the object and returns its path
    codepath =LibQRCode.generate_qrcode(self.id.to_s + "#" + self.user.id.to_s + "#"  + self.user.first_name + " "+self.user.last_name, {:size => 3}) # size 2 will fit a 24 char string which is enough
    
    # save image path
    self.update_attribute(:qrcode, codepath)
  end
  
  
  def full_address 
    return self.street + ", " + self.city + ", "+ self.country
  end
  
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  
  before_filter :authenticate_user!
  
  
  # GET /mailboxes
  # GET /mailboxes.json
  def index
    @mailboxes = current_user.mailboxes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailboxes }
    end
  end

  # GET /mailboxes/1
  # GET /mailboxes/1.json
  def show
    @mailbox = Mailbox.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailbox }
    end
  end

  # GET /mailboxes/new
  # GET /mailboxes/new.json
  def new
    @mailbox = Mailbox.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailbox }
    end
  end
  
  def edit
    @mailbox = Mailbox.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailbox }
    end
  end


  # POST /mailboxes
  # POST /mailboxes.json
  def create
    @mailbox = Mailbox.new(params[:mailbox])
    @mailbox.user = current_user

    respond_to do |format|
      if @mailbox.save
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully created.' }
        format.json { render json: @mailbox, status: :created, location: @mailbox }
      else
        format.html { render action: "new" }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /mailboxes/1
  # DELETE /mailboxes/1.json
  def destroy
    @mailbox = Mailbox.find(params[:id])
    @mailbox.destroy

    respond_to do |format|
      format.html { redirect_to mailboxes_url }
      format.json { head :no_content }
    end
  end
  
  
  
  def community
    @mailboxes = current_user.mailboxes
  end
  
  def nearby
    @mailbox = Mailbox.find(params[:id])
    distance_in_miles = (params[:distance]) ? params[:distance].to_f * 0.62137 : 0.62137
    @search = {}
    @search[:radius] = params[:distance] || 1
    @search[:latitude] = @mailbox.latitude
    @search[:longitude] = @mailbox.longitude
    
    if @mailbox.geocoded?
      @nearby = @mailbox.nearbys(distance_in_miles)                      
    end
    
    respond_to do |format|
      format.json
    end
    
    
  end
  
  

  
  
  
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<%= form_for(@mailbox) do |f| %>
  <% if @mailbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailbox.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
      <% @mailbox.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
   <div class="line_grid">
	<div class="g_3"><%= f.label :name %> *</div>
	<div class="g_9">
		<%= f.text_field :name %>
		<div class="field_notice">Assign a name to this mailbox</div>
	</div>
  </div>
  
  <div class="line_grid">
	<div class="g_3"><%= f.label :street %> *</div>
	<div class="g_9">
		<%= f.text_field :street %>
	</div>
  </div>
							
<div class="line_grid">
	<div class="g_3"><%= f.label :city %> *</div>
	<div class="g_9">
		<%= f.text_field :city %>
	</div>
  </div>
  
  
  <div class="line_grid">
	<div class="g_3"><%= f.label :country %> *</div>
	<div class="g_9">
		<%= f.text_field :country %>
	</div>
  </div>
  
   <div class="line_grid">
	<div class="g_3"><%= f.submit %></div>
  </div>
  
<% end %>

app/views/mailboxes/community.html.erb
<% content_for :head do %>
  
<script type="text/javascript">
$(function() {
    makeTabActive("community");
    //initialize();
    
    });
</script>

<!--
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwOx801Flp99VY2MhGlhi937dCqV0MIyQ&sensor=false">
 </script>
-->


<script type="text/javascript">

  var map;
  
  function initialize() {
    var mapOptions = {
	    zoom: 12,
	    center: new google.maps.LatLng(48.8550, 2.3470),
	    mapTypeId: google.maps.MapTypeId.ROADMAP
	  }
	  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
	  
	  // reset peoples name
	  $("#people").html("");
	  
	}
	
	
	var loaded = false;
	function loadScript() {
		if (loaded) { getNearby(); return; }
	  var script = document.createElement("script");
	  script.type = "text/javascript";
	  script.src = "http://maps.googleapis.com/maps/api/js?key=AIzaSyDwOx801Flp99VY2MhGlhi937dCqV0MIyQ&sensor=false&callback=getNearby";
	  document.body.appendChild(script);
	  loaded = true;
	}
	
	
	
	
	function getNearby(){
		
		if (!loaded) { loadScript(); return } // load map before if not loaded
		
		initialize(); // initialize, or re-
		
		$("#people-list").show();
		
		var mailboxId = $("#mailbox-select").val();
		var distance = $("#distance-input").val();
		
		$.getJSON('/mailboxes/'+mailboxId+'/nearby?distance='+distance+'&format=json',function(data){
			
			
			 if (data.mailboxes) {
			 	$("#count-results").text("("+data.mailboxes.length+")");
			 	
		         for(var i=0;i<data.mailboxes.length;i++){
		         	
		         	var ownerName = data.mailboxes[i].mailbox.user.name;
		            var myLatlng = new google.maps.LatLng(data.mailboxes[i].mailbox.latitude,data.mailboxes[i].mailbox.longitude);
		            
		            var marker = new google.maps.Marker({
					      position: myLatlng,
					      map: map,
					      title:ownerName
					});
					
					
					// append person's name to the list
					$("#people").append("<li>"+ownerName+"</li>")
					
		        }
	      } else $("#count-results").text("(0)");
	        
	         var centerSearch = new google.maps.LatLng(data.latitude, data.longitude);
			
			 var circle = new google.maps.Circle({
	           map: map,
	           radius: data.radius*1000, // 3000 km
	           center: centerSearch,
	           strokeColor: "#0000FF",
		       strokeOpacity: 0.6,
		       strokeWeight: 2,
		       fillColor: "#0000FF",
		       fillOpacity: 0.20,
	         });

	        
    	});
	}
	
	
</script>


<% end %>




				<!-- options -->
				<div class="g_12">
					
					<h1>Nearby mailboxes <span id="count-results"></span></h1>
					
						<div style="float: left;">
							<label> Select your mailbox: </label>
							<select id="mailbox-select">
							<%= options_from_collection_for_select(@mailboxes, :id, :name) %>
							</select>
						</div>
						
						<div style="float: left; margin-left: 20px;">
							<label> Radius: </label>
							<input type="text" value="1" id="distance-input" name="distance-input" maxlength="3" style="width: 30px;"/>Km
							<button onclick="getNearby();">OK</button>
						</div>
					
				</div>
				
				
				
				<div class="g_12" id="map_canvas" style="height:500px"></div>

				<div id="people-list" class="g_12" style="display:none;">
					<h1>Nearby people</h1>
					<ul id="people" style="display: inline; list-style-type: none; padding-right: 20px;"></ul>
				</div>

app/views/mailboxes/edit.html.erb
<h1>Edit mailbox</h1>

<%= render 'form' %>

<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/index.html.erb
<script type="text/javascript">
$(function() {
    makeTabActive("mailbox");
    });

</script>



				
				



				<!-- Charts -->
				<div class="g_12">
					
					<h2>Listing my mailboxes</h2>

				<table id="table-mailboxes" class="tables ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
				  <tr>
				    <th>Name</th>
				    <th>Print</th>
				    <th>Edit</th>
				    <th>Delete</th>
				  </tr>
				
				<% @mailboxes.each do |mailbox| %>
				  <tr>
				    <td><%= mailbox.name %></td>
				    <td><%= link_to('Print sticker', path_to_image("../"+mailbox.qrcode)) %></td>
				    <td><%= link_to 'Edit', edit_mailbox_path(mailbox) %></td>
				    <td><%= link_to 'Delete', mailbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				  </tr>
				<% end %>
				</table>

					
				</div>
				

				<div class="g_6 contents_options">
						 <%= link_to 'Add Mailbox', new_mailbox_path, :class=>"simple_buttons" %> 
					
				</div>

app/views/mailboxes/new.html.erb
<h1>Add mailbox</h1>

<%= render 'form' %>

<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mailbox.name %>
</p>

<p>
  <b>Qrcode:</b>
  <%= image_tag "../"+@mailbox.qrcode %>
</p>


<%= link_to 'Back', mailboxes_path %>